[package]
name = "json"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish.workspace = true

[features]
sonic = ["dep:sonic-rs"]
avx512 = ["sonic", "sonic-rs/avx512"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
sonic-rs = { workspace = true, optional = true }

[lints]
workspace = true
