[package]
name = "ptbs"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
iota-json-rpc-api = { workspace = true }
iota-json-rpc-types = { workspace = true }
iota-sdk = { workspace = true }
iota-sdk-types = { workspace = true }
iota-types = { workspace = true }
move-core-types = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }

[lints]
workspace = true
