[package]
name = "dex"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
crypto = { workspace = true }
iota-json-rpc-types = { workspace = true }
iota-sdk = { workspace = true }
iota-sdk-types = { workspace = true }
iota-types = { workspace = true }
ptbs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
networks = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
